### ISSUE TITLE
https://fitsleepinsights.app/

### ISSUE THREAD

**Issue by DrcspyNz** [galeone/fitsleepinsights#20]
Getting 'internal server error' on login attempt

**Comment by galeone** [comment]
Hi @DrcspyNz do you still have this problem?

I'm trying to replicate it but with my account, I can log in.

**Comment by galeone** [comment]
Fixed by https://github.com/galeone/fitsleepinsights/commit/7bbda5ad49ea1de3aa02792d18296c2e8ae1e4a9
